export default {
	profile: require('../assets/louvre.png'),
	dooty: require('../assets/dootyboi.gif'),
	skeleton_army: require('../assets/skeleton_army.jpg'),
	bones: require('../assets/bones.jpg'),
	shoggoth: require('../assets/shoggoth.jpg'),
	skelethumb: require('../assets/skelethumb.png'),
	doot: require('../assets/doot.png'),
	dootier: require('../assets/dootier.gif'),
	dealWithIt: require('../assets/deal_with_it.gif'),
	spookyBG: require('../assets/spooky_bg.jpg'),
	skeleMobile: require('../assets/skele-mobile.jpg'),
	spookyAsylumBG: require('../assets/spooky_asylum_bg.jpg'),
	hauntedHouseBG: require('../assets/haunted_house_bg.jpg'),
	halloweenBG: require('../assets/halloween_bg.jpg'),
	rattleMeBones: require('../assets/rattle-me-bones.gif'),
	city: require('../assets/city.jpg'),
	kat: require('../assets/kat.png'),
	throwSkull: require('../assets/throw_skull.gif'),
	skeletonDance: require('../assets/skeletondance.gif'),
	logo: require('../assets/formidable-logo.svg'),
	markdown: require('../assets/markdown.png'),
	barchart2: require('../assets/bar_chart2.png'),
	radial_chart: require('../assets/radial_chart.png'),
	streamgraph: require('../assets/streamgraph.png'),
	mapBase: require('../assets/map.png'),
	mapMs: require('../assets/map-ms.png'),
	mapMsSilverdale: require('../assets/map-ms-silverdale.png'),
	healthcare: require('../assets/healthcare.png'),
	narcissism: require('../assets/narcissism.jpg'),
	dcu: require('../assets/dcu.jpg'),
	network: require('../assets/network.png'),
	ourteam: require('../assets/our-team.png'),
	ourteam2: require('../assets/our-team-2.png'),
	visualSurvey: require('../assets/visual-survey.png'),
	winchester: require('../assets/winchester.gif'),
	npmsearch: require('../assets/npm_search.png'),
	lumbergh: require('../assets/lumbergh.gif'),
	rage: require('../assets/rage.png'),
	angry_dooting: require('../assets/angry_dooting.gif'),
	missingAbstraction: require('../assets/missing_abstraction.png'),
	wilkinson: require('../assets/wilkinson_book.jpg'),
	analogy: require('../assets/analogy.png'),
	markencoding: require('../assets/mark_encoding.png'),
	reactlogo: require('../assets/react-logo.png'),
	vegapage: require('../assets/vega-page.png'),
	altairpage: require('../assets/altair-page.png'),
	barchartwithmean: require('../assets/bar_chart_with_mean.png'),
	chartPartsPage: require('../assets/chart-parts-page.png'),
	chriswhite: require('../assets/chris_white.jpg'),
	barchartapi: require('../assets/barchart_api.png'),
	hans: require('../assets/hans.gif'),
	d3: require('../assets/d3.png'),
	pipboy: require('../assets/pipboy.png'),

	// Common Charts
	barChart: require('../assets/bar_chart.png'),
	lineChart: require('../assets/line_chart.png'),
	pieChart: require('../assets/pie_chart.png'),
	areaChart: require('../assets/area_chart.png'),
	radarChart: require('../assets/radar_chart.png'),
	violinChart: require('../assets/violin_chart.png'),
	boxPlots: require('../assets/box_plots.png'),

	// Victory
	victory: require('../assets/victory.png'),
	victoryApi: require('../assets/victory-api.png'),
	victoryCustom: require('../assets/victory-custom.png'),
	victoryComposable: require('../assets/victory-composable.png'),
	victoryCircle: require('../assets/victory-circle.png'),

	// React-Vis
	reactVisPage: require('../assets/reactvis-page.png'),
	reactVisApi: require('../assets/reactvis-apiseries.png'),
	reactVisCanvas: require('../assets/reactvis-canvas.png'),

	// Recharts
	rechartsPage: require('../assets/recharts-page.png'),
	rechartsCustom: require('../assets/recharts-customizable.png'),
	rechartsDatabind: require('../assets/recharts-databind.png'),
	rechartsCustomChart: require('../assets/recharts-customchart.png'),
	rechartsTaxonomical: require('../assets/recharts-taxonomical.png'),

	// ChartParts
	backendArchitecture: require('../assets/lib-backend.png'),
	frontendArchitecture: require('../assets/lib-frontend.png'),

	ast: require('../assets/ast.png'),
	dataflow: require('../assets/dataflow.png'),
	dropout: require('../assets/dropout.png'),
}
